(()=>{
const defaults={room_width:500,room_depth:400,room_height:250,sofa_width:200,sofa_depth:90,sofa_height:85,x:250,y:200,rotation:0,room_accuracy:'estimated',sofa_accuracy:'estimated'};
const host=document.querySelector('#placement');
host.innerHTML=`<h2>3. Plan sofa placement</h2><p>All dimensions are in centimetres. The initial values are examples, not measurements of your photo. The rectangle represents the sofa's full footprint. This plan is separate from the room photo.</p><p id="layout-product">No sofa selected — using a generic footprint.</p><div class="dimension-grid"><fieldset><legend>Room dimensions</legend>${field('room_width','Width',50,5000)}${field('room_depth','Depth',50,5000)}${field('room_height','Ceiling height',100,1000)}${accuracy('room_accuracy')}</fieldset><fieldset><legend>Sofa dimensions</legend>${field('sofa_width','Width',20,1000)}${field('sofa_depth','Depth',20,1000)}${field('sofa_height','Height',10,500)}${accuracy('sofa_accuracy')}</fieldset><fieldset><legend>Position of sofa centre</legend>${field('x','X from left wall',-5000,10000)}${field('y','Y from top wall',-5000,10000)}${field('rotation','Rotation (degrees)',0,359)}<button id="rotate-sofa">Rotate 90°</button><button id="centre-sofa">Centre sofa</button></fieldset></div><p>Drag the sofa or use the position fields. Its labelled front shows which way it faces.</p><svg id="floorplan" role="img" aria-label="Scaled top-down room and movable sofa" style="width:100%;height:480px;background:#e9e7df;touch-action:none;border-radius:12px"></svg><p id="fit-status" role="status"></p><p>Checks cover room boundaries and ceiling height only. Doors, walkways and remaining furniture are not included.</p><button class="primary" id="save-layout">Save layout</button><p id="layout-status" role="status">Example layout — not saved.</p>`;
function field(id,label,min,max){return `<label>${label}<input aria-label="${id.replaceAll('_',' ')}" id="layout-${id}" type="number" min="${min}" max="${max}" step="1" value="${defaults[id]}"></label>`;}
function accuracy(id){return `<label>Measurements<select id="layout-${id}" aria-label="${id.replaceAll('_',' ')}"><option value="estimated">Estimated</option><option value="measured">Measured / verified</option></select></label>`;}
const svg=document.querySelector('#floorplan'),ns='http://www.w3.org/2000/svg';let layout={...defaults},drag=null,valid=true;
function el(tag,attrs,text){const n=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);if(text)n.textContent=text;return n;}
function read(){const next={};for(const k of Object.keys(defaults)){const input=document.querySelector('#layout-'+k);if(input.type==='number'&&(!input.value||!input.checkValidity()))throw Error('Enter valid positive dimensions and a rotation from 0 to 359.');next[k]=input.type==='number'?Number(input.value):input.value;}return next;}
function setFields(){for(const k of Object.keys(defaults))document.querySelector('#layout-'+k).value=layout[k];}
function render(){const w=layout.room_width,d=layout.room_depth,pad=Math.max(w,d)*.12;svg.replaceChildren();svg.setAttribute('viewBox',`${-pad} ${-pad} ${w+2*pad} ${d+2*pad}`);svg.append(el('rect',{x:0,y:0,width:w,height:d,fill:'#fffdf5',stroke:'#536759','stroke-width':3}));for(let x=100;x<w;x+=100)svg.append(el('line',{x1:x,y1:0,x2:x,y2:d,stroke:'#e1e5dd'}));for(let y=100;y<d;y+=100)svg.append(el('line',{x1:0,y1:y,x2:w,y2:y,stroke:'#e1e5dd'}));svg.append(el('text',{x:w/2,y:-pad*.4,'text-anchor':'middle','font-size':pad*.3},`${w} cm × ${d} cm · grid 100 cm`));const a=layout.rotation*Math.PI/180,hx=(Math.abs(Math.cos(a))*layout.sofa_width+Math.abs(Math.sin(a))*layout.sofa_depth)/2,hy=(Math.abs(Math.sin(a))*layout.sofa_width+Math.abs(Math.cos(a))*layout.sofa_depth)/2;const fits=layout.x-hx>=-1e-6&&layout.y-hy>=-1e-6&&layout.x+hx<=w+1e-6&&layout.y+hy<=d+1e-6&&layout.sofa_height<=layout.room_height;const g=el('g',{transform:`translate(${layout.x} ${layout.y}) rotate(${layout.rotation})`,'data-sofa':'true',style:'cursor:grab'});g.append(el('rect',{x:-layout.sofa_width/2,y:-layout.sofa_depth/2,width:layout.sofa_width,height:layout.sofa_depth,rx:4,fill:fits?'#769682':'#ca7b6e',stroke:'#284c39','stroke-width':2}),el('text',{x:0,y:0,'text-anchor':'middle','font-size':Math.min(layout.sofa_width/10,18)},`${layout.sofa_width} × ${layout.sofa_depth}`),el('text',{x:0,y:layout.sofa_depth/2-8,'text-anchor':'middle','font-size':12},'FRONT ↓'));svg.append(g);document.querySelector('#fit-status').textContent=fits?'Fits within the entered room dimensions. Accuracy depends on your measurements.':'Does not fit: the sofa crosses a room boundary or exceeds ceiling height.';}
function change(){try{layout=read();valid=true;render();document.querySelector('#layout-status').textContent='Unsaved changes.';}catch(e){valid=false;document.querySelector('#layout-status').textContent=e.message;}}
host.querySelectorAll('input,select').forEach(n=>n.addEventListener('input',change));
document.querySelector('#rotate-sofa').onclick=()=>{if(!valid)return;layout.rotation=(layout.rotation+90)%360;setFields();change();};document.querySelector('#centre-sofa').onclick=()=>{if(!valid)return;layout.x=layout.room_width/2;layout.y=layout.room_depth/2;setFields();change();};
function point(e){return new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse());}
svg.onpointerdown=e=>{if(!valid||!e.target.closest('[data-sofa]'))return;const p=point(e);drag={x:p.x-layout.x,y:p.y-layout.y};svg.setPointerCapture(e.pointerId);};svg.onpointermove=e=>{if(!drag)return;const p=point(e);layout.x=Math.round(p.x-drag.x);layout.y=Math.round(p.y-drag.y);setFields();change();};svg.onpointerup=svg.onpointercancel=()=>drag=null;
document.querySelector('#save-layout').onclick=async()=>{try{const value=read();const r=await fetch('/layout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});const data=await r.json();if(!r.ok)throw Error(data.error);document.querySelector('#layout-status').textContent='Layout saved'+(data.layout.fits?'.':' with an out-of-bounds warning.');}catch(e){document.querySelector('#layout-status').textContent=e.message;}};
function product(p){document.querySelector('#layout-product').textContent=p?'Selected sofa: '+p.name+'. Enter dimensions for this exact variant.':'No sofa selected — using a generic footprint.';}
window.addEventListener('room-state',e=>product(e.detail.selected_product));
render();fetch('/state').then(r=>r.json()).then(s=>{product(s.selected_product);if(s.layout){layout={...defaults,...s.layout};setFields();render();document.querySelector('#layout-status').textContent='Saved layout restored.';}}).catch(()=>{document.querySelector('#layout-status').textContent='Could not restore saved layout.';});
})();
